language: go

go:
  - 1.16.x
  - 1.17.x
  - 1.18.x
  - 1.19.x

git:
  depth: 1

matrix:
  fast_finish: true

before_install:
  - go get github.com/mgechev/revive

script:
  - test -z "$(revive -config revive.toml .)"
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
